# Machine Learning - Assignment 1

### Oscar Fabián Ñáñez Núñez - Juan Camilo Calero Espinoza
### ofnanezn - jccaleroe

## 1) Online course 
<br>
<img src="image.png"></img>



## 2) Probability and Linear Algebra

In [1]:
import numpy as np

In [2]:
TD = np.array([[2.,3.,0.,3.,7.],
               [0.,5.,5.,0.,3.],
               [5.,0.,7.,3.,3.],
               [3.,1.,0.,9.,9.],
               [0.,0.,7.,1.,3.],
               [6.,9.,4.,6.,0]])

L = np.array([[5,2,3,6,4,3]]).T

print("TD Matrix:")
print(TD)
print("\nVector L:")
print(L)

TD Matrix:
[[2. 3. 0. 3. 7.]
 [0. 5. 5. 0. 3.]
 [5. 0. 7. 3. 3.]
 [3. 1. 0. 9. 9.]
 [0. 0. 7. 1. 3.]
 [6. 9. 4. 6. 0.]]

Vector L:
[[5]
 [2]
 [3]
 [6]
 [4]
 [3]]


## Notation:
Let $\bf{1^{i}}$ be a columnar vector of ones with length i. <br>
We'll treat $TD$ as a matrix of size $n \times m$. <br>
When using indexes, $i$ will refer to rows and $j$ will refer to columns. <br>
We are using broadcasting inside mathematical notation. <br>
$*$ operator will refer to element-wise multiplication. <br>
$\times$ operator will refer to matrices dot product. <br>
$A^t$ will denote the transpose of matrix/vector A <br>
$diag(v)$ will refer to the Diagonal matrix of vector $v$. <br>
$\frac {1}{M}$ is equivalent to $\frac {1}{m_{ij}} \space \forall m_{ij} \in M$ 

## a)
Mathematical expression: <br>
    &emsp;&emsp;$P(T,D) = P(D) \times P(T|D) = \frac{1}{5} * \frac{TD}{\sum_i TD} = \frac{1}{5} * TD \times diag(\frac{1}{(\mathbf{1^{n}})^t \times TD}) $

In [3]:
np.ones((1,6))

array([[1., 1., 1., 1., 1., 1.]])

In [3]:
def PTD(TD):
    return (1/5) * (np.dot(TD, np.diagflat(1/np.dot(np.ones((1,6)), TD))))

P_TD = PTD(TD)
print(P_TD)

[[0.025      0.03333333 0.         0.02727273 0.056     ]
 [0.         0.05555556 0.04347826 0.         0.024     ]
 [0.0625     0.         0.06086957 0.02727273 0.024     ]
 [0.0375     0.01111111 0.         0.08181818 0.072     ]
 [0.         0.         0.06086957 0.00909091 0.024     ]
 [0.075      0.1        0.03478261 0.05454545 0.        ]]


## b)    
Mathematical expression: <br>
    &emsp;&emsp;$P(T|D) = \frac{TD}{\sum_i TD} = TD \times diag(\frac{1}{(\mathbf{1^{n}})^t \times TD}) $

In [4]:
def PTgD(TD):
    return np.dot(TD, np.diagflat(1/np.dot(np.ones((1,6)), TD)))

P_TgD = PTgD(TD)
print(P_TgD)

[[0.125      0.16666667 0.         0.13636364 0.28      ]
 [0.         0.27777778 0.2173913  0.         0.12      ]
 [0.3125     0.         0.30434783 0.13636364 0.12      ]
 [0.1875     0.05555556 0.         0.40909091 0.36      ]
 [0.         0.         0.30434783 0.04545455 0.12      ]
 [0.375      0.5        0.17391304 0.27272727 0.        ]]


## c) 
Mathematical expression: <br>
        &emsp;&emsp;$P(D|T) = \frac {P(T,D)} {P(T)}= \frac{P(T,D)}{\sum_j P(T,D)} = diag(\frac{1}{P(T,D) \times \mathbf{1^m}}) \times P(T,D)$

In [5]:
def PDgT(P_TD):
    return np.dot(np.diagflat(1/np.dot(P_TD,np.ones((5,1)))),P_TD)
    
P_DgT = PDgT(P_TD)
print(P_DgT)

[[0.17654612 0.23539482 0.         0.19259576 0.3954633 ]
 [0.         0.45154704 0.35338464 0.         0.19506832]
 [0.35787437 0.         0.34853851 0.15616336 0.13742376]
 [0.18524987 0.05488885 0.         0.40418153 0.35567975]
 [0.         0.         0.64782097 0.09675248 0.25542655]
 [0.28373832 0.37831776 0.13158879 0.20635514 0.        ]]


## d)
Mathematical expression: <br>
        &emsp;&emsp;$P(D)_j = \frac {1}{m} \hspace{0.3cm} \forall j \hspace{0.1cm}$ where $m$ is the number of columns of matrix $TD$ and $P(D)$ is a vector of size $m$

In [10]:
def PD():
    return np.array([1/TD.shape[1]]*TD.shape[1])

P_D = PD()
print(P_D)
TD.shape

[0.2 0.2 0.2 0.2 0.2]


(6, 5)

## e)
Mathematical expression: <br>
        &emsp;&emsp;$P(T) = \sum_i P(T,D) = P(T,D) \times \mathbf{1^m}$

In [7]:
def PT(PTD):
    return np.dot(P_TD,np.ones((5,1)))

P_T = PT(P_TD)
print(P_T)

[[0.14160606]
 [0.12303382]
 [0.17464229]
 [0.20242929]
 [0.09396047]
 [0.26432806]]



## f)
Mathematical expression: <br> 
        &emsp;&emsp;$P(l) = P(T)$ <br>
        &emsp;&emsp;$\mathbf{E}[l] = \sum_i L_i \times P(l_i) = L^{t} \times P(l)$

In [8]:
def E(l, P_T):
    return np.dot(l.T, P_T)

print(E(L, P_T))

[[3.86142666]]



## g)
Mathematical expression:    
    &emsp;&emsp;$Var(l) = \sum_{i} P(l_{i})*(L_{i}-\mu_{L})^2 = (L^{t}-\mu_{L})^{2} \times P(T) \quad$ where $\mu_{L}$ is a vector with a same size than $L$ and which contains the mean in every position, and the square refers to element-wise power of two

In [9]:
def var(l, p):
    return np.dot(np.square(l.T-np.mean(l)), p)

print(var(L, P_T))

[[1.86401552]]
