# Quiz 2
# Machine Learning 2018-1

____________________
A support vector machine (SVM) was trained with a particular dataset using this kernel $k(x,y)=(<x,y>+2)^{2}$. As a result,
five support vectors were obtained: $x_{1}=(1,2)$, $x_{2}=(3,1)$,  $x_{3}=(0,1)$, $x_{4}=(2,0)$ and $x_{5}=(0,0)$, with labels $y_{1}=1$, $y_{2}=1$, $y_{3}=-1$, $y_{4}=-1$  and $y_{5}=-1$ respectively. The $\alpha$ values were $\alpha_1 =0.0763$, $\alpha_2 = 0.0026 $, $\alpha_3 =0.0643$, $\alpha_4 =0.0146$ and $\alpha_5 =0.4017$. 


### 1. (1.5) 

Design a function that calculates the discriminant function for the SVM.

In [1]:
import numpy as np

In [2]:
def compare(val1, val2, error):
    if abs(val1 - val2) > error:
        return False
    return True

def compare_array(array1, array2, error):
    if array1.shape != array2.shape :
        return False
    ar1 = np.array(array1)
    ar2 = np.array(array2)
    ar1.sort()
    ar2.sort()
    for i in range(ar1.shape[0]):
        if not compare(ar1[i], ar2[i], error):
            return False
    return True

X = np.array([[1, 2], [3, 1], [0,1], [2,0], [0,0]])
y = np.array([1, 1, -1, -1, -1])
alpha = np.array([0.0763, 0.0026, 0.0643, 0.0146, 0.4017])
X_test = np.array([[1, 2], [3, 1], [0,1], [2,0], [0,0], [-1,2], [2, -3]])
y_test = np.array([ 0.9969,  0.9932, -0.9997, -1.0024, -1.6068, -0.7255, -1.8265])
ws = [np.array([0.0997    , 0.3078    , 0.22683986, 0.1682    , 0.3104    ,
        0.1578    ]),
 np.array([0.0997    , 0.2435    , 0.22683986, 0.1682    , 0.1818    ,
        0.0292    ]),
 np.array([4.13000000e-02, 2.43500000e-01, 2.26839855e-01, 1.09800000e-01,
        1.81800000e-01, 3.12250226e-17]),
 np.array([ 0.0413    ,  0.2435    ,  0.22683986,  0.1098    ,  0.1818    ,
        -0.8034    ])]

### 1. (1.5) 

Design a function that calculates the discriminant function for the SVM.

In [5]:
def discriminant(x, X, y, alpha):
    '''
    x: the sample to classify (numpy array of shape (2,))
    X: support vectors (numpy array of shape (n, 2))
    y: labels of the support vectors (numpy array of shape (n,))
    alpha: coefficients for the support vectors (numpy array of shape (n,))
    returns the value of the SVM discriminant function evaluated on x
    '''
    print(np.dot(X, x))
    return np.sum(y*alpha*(np.dot(x, X.T)+2)**2)

In [6]:
def t1():
    for i in range(X_test.shape[0]):
        if not compare(y_test[i], discriminant(X_test[i], X, y, alpha), 0.001):
            return False
    return True
t1()

[5 5 2 2 0]
[ 5 10  1  6  0]
[2 1 1 0 0]
[2 6 0 4 0]
[0 0 0 0 0]
[ 3 -1  2 -2  0]
[-4  3 -3  4  0]


True

### 2. (2.0)
Design a function that maps a sample in the input space to the feature space induced by the kernel $k(x,y)=(<x,y>+2)^{2}$.

In [42]:
def phi(x):
    '''
    x: a sample in the input space (numpy array of shape (2,))
    returns a vector in the feature space corresponding to the image of x (numpy array of shape (6,))
    '''
    result = np.zeros(6)
    result[0] = (x[0]*x[0])
    result[1] = np.sqrt(2)*x[0]*x[1]
    result[2] = 2*x[0]
    result[3] = (x[1]*x[1])
    result[4] = 2*x[1]
    result[5] = 2 
    return result

def t2():
    for i in range(X_test.shape[0] ):
        for j in range(i, X_test.shape[0]):
            phi1 = phi(X_test[i])
            phi2 = phi(X_test[j])
            dot1 = (np.dot(X_test[i], X_test[j]) + 2) ** 2
            dot2 = np.dot(phi1, phi2)            
            if not compare(dot1, dot2, 0.001):
                return False
    return True
t2()

True

### 3. (1.5)

Design a function that calculates the $w$ vector that determines the separation hyperplane in the feature space.

In [59]:
def calculate_w(X, y, alpha):
    '''
    X: support vectors (numpy array of shape (n, 2))
    y: labels of the support vectors (numpy array of shape (n,))
    alpha: coefficients for the support vectors (numpy array of shape (n,))
    returns the vector w in the feature space that defines the separating hyperplane (numpy array of shape (6,))
    '''
    w = np.zeros(6)    
    for i in range(X.shape[0]):
        w += phi(X[i])*y[i]*alpha[i]    
    return w

def t3():
    for i in range(2, X.shape[0] + 1):        
        if not compare_array(calculate_w(X[:i], y[:i], alpha[:i]), ws[i-2], 0.001):
            return False
    return True
t3()

True

In [60]:
def evaluate():
    score = 0 
    tests = [t1, t2, t3]
    vals = [1.5, 2, 1.5]
    for i in range(len(tests)):
        if tests[i]():
            score += vals[i]
    return score

print ("Score: ", evaluate(), "/ 5.0")

Score:  5.0 / 5.0
